### ISSUE TITLE
Wrong feeder pcb ? N20-GND is connected  to NO or NC?

### ISSUE THREAD

**Issue by indexdb** [CurlyTaleGamesLLC/MAXFeederShield#1]
When the power is turned on, the N20 motor turns continuously. I checked the schematic of the feeder and N20-GND is connected to the NC of the limit switch (Normally closed). So, by default N20-GND is connected  to GND and N20-5v connect to +5V , so as soon as the power is turned on, the N20d motor starts to work.
I think N20-GND should connect to NO terminal of the limit switch.

**Comment by CurlyTaleGames** [comment]
Hi indexdb, 

That microswitch is doing a lot of things, and the circuit definitely looks odd, but it's normal for the n20 motor to run if there isn't any tape loaded. When the cover tape pulls down on the tape lever it presses the microswitch which disconnects power to the motor.

If you haven't loaded tape into the feeder and don't want the motor to spin all the time, you can either unplug the n20 motor or what I like to do is wedge some male header under the 3d printed lever arm. That will keep the microswitch held down so power isn't being sent to the motor.

Thanks!
-Ben
